### ISSUE TITLE
Log Signer crashes via nil defer on exit

### ISSUE THREAD

**Issue by Martin2112** [google/trillian#1192]
Looks related to recent changes. Can end up callng defer with nil etcd client, which later crashes.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x128 pc=0x9ce7a6]
goroutine 1 [running]:
github.com/google/trillian/vendor/github.com/coreos/etcd/clientv3.(*Client).Close(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/google/trillian/vendor/github.com/coreos/etcd/clientv3/client.go:96 +0x26
main.main()
	/home/travis/gopath/src/github.com/google/trillian/server/trillian_log_signer/main.go:165 +0x9fe
Stopping Log RPC server (pid 20038)
```

**Comment by daviddrysdale** [comment]
Introduced in 7d715ea8d9a6aa6e1298cfa4e9d5edfa3372abdf; I suspect it just needs an `if client != nil { }` around it.

**Comment by pavelkalinnikov** [comment]
I will fix it, thanks for discovering.

**Comment by pavelkalinnikov** [comment]
I believe this is fixed now.
