### ISSUE TITLE
TX rollback error: sql: transaction has already been committed or rolled back

### ISSUE THREAD

**Issue by RJPercival** [google/trillian#1587]
I've seen the following warning amongst the logs for `github.com/google/trillian/testonly/hammer` when it fails. This suggests that there's either multiple Rollback() calls, or a Commit() and Rollback() call, occurring on a single transaction in the map code.

```
W0513 09:33:42.146958   20550 tree_storage.go:429] TX rollback error: sql: transaction has already been committed or rolled back, stack:
goroutine 75 [running]:
runtime/debug.Stack(0xc000793180, 0xe85240, 0xc000053700)
	/home/travis/.gimme/versions/go1.11.10.linux.amd64/src/runtime/debug/stack.go:24 +0xa7
github.com/google/trillian/storage/mysql.(*treeTX).rollbackInternal(0xc000990900, 0xde4520, 0xc0006fdb98)
	/home/travis/gopath/src/github.com/google/trillian/storage/mysql/tree_storage.go:429 +0x5c
github.com/google/trillian/storage/mysql.(*treeTX).Close(0xc000990900, 0x0, 0x0)
	/home/travis/gopath/src/github.com/google/trillian/storage/mysql/tree_storage.go:440 +0x82
github.com/google/trillian/storage/mysql.(*mySQLMapStorage).ReadWriteTransaction(0xc0003510e0, 0xe934c0, 0xc000316450, 0xc00042e140, 0xc000b3da60, 0xe85240, 0xc000d7e1f0)
	/home/travis/gopath/src/github.com/google/trillian/storage/mysql/map_storage.go:154 +0x14a
github.com/google/trillian/server.(*TrillianMapServer).SetLeaves.func1.1(0xe934c0, 0xc000316450, 0xc000b3da60, 0xc, 0xe934c0)
	/home/travis/gopath/src/github.com/google/trillian/server/map_rpc_server.go:307 +0x184
github.com/google/trillian/merkle.(*subtreeWriter).buildSubtree(0xc0007403f0, 0xe934c0, 0xc000316450, 0x400)
	/home/travis/gopath/src/github.com/google/trillian/merkle/sparse_merkle_tree.go:217 +0x166
created by github.com/google/trillian/merkle.newLocalSubtreeWriter
	/home/travis/gopath/src/github.com/google/trillian/merkle/sparse_merkle_tree.go:358 +0x260
W0513 09:33:42.146975   20550 tree_storage.go:442] Rollback error on Close(): sql: transaction has already been committed or rolled back
```

**Comment by AlCutter** [comment]
Don't think we've seen this for quite a while now.
